version: 2
jobs:
  build_and_deploy:
    steps:
      - name: Install Dependencies
        script:
          - pip install -r requirements.txt
      - name: Run Tests
        script:
          - pytest
      - name: Deploy to Razorops
        script:
          - razor deploy
